steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'my-function'
    - '--runtime'
    - 'python310'
    - '--trigger-topic'
    - 'input_topic'
    - '--entry-point'
    - 'main'
    - '--region'
    - 'asia-south1'

- name: 'curlimages/curl'
  args:
    - '-u'
    - 'adjkuser:Qwertyuiop20!'
    - 'http://34.93.56.159:8080/job/cloudfunction/build'
